version: '3'

services:
  api:
    build: './api'
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=${MONGO_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_URI=${AUTH0_ISSUER_URI}
    depends_on: 
      - ai_service
    restart: always
  
  embedding_worker:
    build: './embedding_worker'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    restart: always

  ai_service:
    build: './ai_service'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    restart: always
