version: '3'

services:
  api:
    build: './api'
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=${MONGO_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_URI=${AUTH0_ISSUER_URI}
  
  embedding_engine:
    build: './embedding_engine'
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    restart: always